import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Varun Gaikwad | Sky Cast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="bg-primary font-mont text-text p-8">
      <body className={inter.className}>
        {children}
        <footer className="fixed bottom-4 right-4 bg-white bg-opacity-30 rounded-lg shadow-md p-4">
          <p className="text-sm font-semibold">
            Data © <a href="http://osm.org/copyright">OpenStreetMap</a>{" "}
            contributors, ODbL 1.0.
          </p>
        </footer>
      </body>
    </html>
  );
}
